
before_install:
  - sudo apt-get update
  - sudo apt-get install aspell-es
  - sudo apt-get install aspell-en
  - cp .aspell.en.pws ~/

script: for f in $(find ./ -name '*.txt' -or -name '*.lex' -or -name '*.md'); do cat $f | aspell --lang=en list | aspell --lang=es list |  sort -u; if [ -n "$OUTPUT" ]; then echo $OUTPUT; exit 1; fi; done
